# Your first steps with Julia

## Przemysław Szufel

In [1]:
# Ctrl + ENTER
versioninfo()

Julia Version 1.10.5
Commit 6f3fdf7b36 (2024-08-27 14:19 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 12 × 13th Gen Intel(R) Core(TM) i7-1355U
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, goldmont)
Threads: 1 default, 0 interactive, 1 GC (on 12 virtual cores)
Environment:
  JULIA_DEPOT_PATH = c:\JuliaPkg\Julia-1.10.5
  JULIA_HOME = c:\Julia-1.10.5
  JULIA_VERSION = Julia-1.10.5


In [2]:
pwd()

"C:\\AAABIBLIOTEKA\\NCN2\\SSC2024\\2024_Julia_Krakow\\1_Basics"

In [3]:
using Pkg
Pkg.status() #pkg"status"

Status `C:\AAABIBLIOTEKA\NCN2\SSC2024\2024_Julia_Krakow\Project.toml`
  [1520ce14] AbstractTrees v0.4.5
  [69666777] Arrow v2.7.3
  [6e4b80f9] BenchmarkTools v1.5.0
  [e28b5b4c] Bootstrap v2.4.0
  [336ed68f] CSV v0.10.14
  [49dc2e85] Calculus v0.5.1
  [324d7699] CategoricalArrays v0.10.8
  [8be319e6] Chain v0.6.0
  [5ae59095] Colors v0.12.11
  [992eb4ea] CondaPkg v0.2.23
  [a93c6f00] DataFrames v1.6.1
  [31c24e10] Distributions v0.25.111
  [da1fdf0e] FreqTables v0.4.6
  [38e38edf] GLM v1.9.0
  [28b8d3ca] GR v0.73.7
  [86223c79] Graphs v1.11.2
  [cd3eb016] HTTP v1.10.8
  [7073ff75] IJulia v1.25.0
  [682c06a0] JSON v0.21.4
  [0f8b85d8] JSON3 v1.14.0
  [b964fa9f] LaTeXStrings v1.3.1
  [a1c25ae6] OSMToolset v0.2.2
  [86cd37e6] OpenStreetMapX v0.4.1
  [d3d4fdd0] OpenStreetMapXPlot v0.2.0
  [8314cec4] PGFPlotsX v1.6.1
  [d96e819e] Parameters v0.12.3
  [91a5bcdd] Plots v1.40.8
  [6099a3de] PythonCall v0.9.23
  [2913bbd2] StatsBase v0.34.3
  [f3b207a7] StatsPlots v0.15.7
  [fdbf4ff8] XLSX v0.1

In [4]:
function f(x,y)
    x+y
end

f(x,y) = x+y

f (generic function with 1 method)

In [5]:
f(5,12.5)

17.5

In [6]:
@code_lowered f(5,6)

CodeInfo(
1 ─ %1 = x + y
└──      return %1
)

In [7]:
@code_typed f(4,5)

CodeInfo(
1 ─ %1 = Base.add_int(x, y)::Int64
└──      return %1
) => Int64

In [8]:
@code_llvm f(5,6)

;  @ In[4]:5 within `f`
; Function Attrs: uwtable
define i64 @julia_f_1520(i64 signext %0, i64 signext %1) #0 {
top:
; ┌ @ int.jl:87 within `+`
   %2 = add i64 %1, %0
   ret i64 %2
; └
}


In [9]:
@code_native f(5,6)

	.text
	.file	"f"
	.globl	julia_f_1557                    # -- Begin function julia_f_1557
	.p2align	4, 0x90
	.type	julia_f_1557,@function
julia_f_1557:                           # @julia_f_1557
; ┌ @ In[4]:5 within `f`
	.cfi_startproc
# %bb.0:                                # %top
	push	rbp
	.cfi_def_cfa_offset 16
	.cfi_offset rbp, -16
	mov	rbp, rsp
	.cfi_def_cfa_register rbp
; │┌ @ int.jl:87 within `+`
	lea	rax, [rcx + rdx]
	pop	rbp
	ret
.Lfunc_end0:
	.size	julia_f_1557, .Lfunc_end0-julia_f_1557
	.cfi_endproc
; └└
                                        # -- End function
	.section	".note.GNU-stack","",@progbits


In [10]:
@code_native f(5.1,6)

	.text
	.file	"f"
	.globl	julia_f_1561                    # -- Begin function julia_f_1561
	.p2align	4, 0x90
	.type	julia_f_1561,@function
julia_f_1561:                           # @julia_f_1561
; ┌ @ In[4]:5 within `f`
	.cfi_startproc
# %bb.0:                                # %top
	push	rbp
	.cfi_def_cfa_offset 16
	.cfi_offset rbp, -16
	mov	rbp, rsp
	.cfi_def_cfa_register rbp
; │┌ @ promotion.jl:422 within `+`
; ││┌ @ promotion.jl:393 within `promote`
; │││┌ @ promotion.jl:370 within `_promote`
; ││││┌ @ number.jl:7 within `convert`
; │││││┌ @ float.jl:159 within `Float64`
	vcvtsi2sd	xmm1, xmm1, rdx
; ││└└└└
; ││ @ promotion.jl:422 within `+` @ float.jl:409
	vaddsd	xmm0, xmm1, xmm0
	pop	rbp
	ret
.Lfunc_end0:
	.size	julia_f_1561, .Lfunc_end0-julia_f_1561
	.cfi_endproc
; └└
                                        # -- End function
	.section	".note.GNU-stack","",@progbits


In [11]:
v = [1,2,3,4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [12]:
v3 = [ 3x for x ∈ 1:9] #Python range(1,10)

9-element Vector{Int64}:
  3
  6
  9
 12
 15
 18
 21
 24
 27

In [13]:
v3[1:4]

4-element Vector{Int64}:
  3
  6
  9
 12

In [14]:
v₄= [ √x₁ for x₁ ∈ 1:9]

9-element Vector{Float64}:
 1.0
 1.4142135623730951
 1.7320508075688772
 2.0
 2.23606797749979
 2.449489742783178
 2.6457513110645907
 2.8284271247461903
 3.0

In [15]:
typeof(v₄)

Vector{Float64} (alias for Array{Float64, 1})

In [16]:
eltype(v₄)

Float64

In [17]:
b = Int[]
append!(b, 5)

1-element Vector{Int64}:
 5

In [18]:
c = []

Any[]

In [19]:
c = Complex(1,4)

1 + 4im

In [20]:
typeof(c)

Complex{Int64}

In [21]:
dump(c)

Complex{Int64}
  re: Int64 1
  im: Int64 4


In [22]:
c2=Complex{Float64}(1,4)

1.0 + 4.0im

In [23]:
typeof(c2)

ComplexF64 (alias for Complex{Float64})

In [24]:
dump(c2)

ComplexF64
  re: Float64 1.0
  im: Float64 4.0


In [25]:
c2=Complex{Float32}(1,4)
typeof(c2)

ComplexF32 (alias for Complex{Float32})

In [26]:
x = 1//2 + 1//4

3//4

In [27]:
typeof(x)

Rational{Int64}

In [28]:
dump(x)

Rational{Int64}
  num: Int64 3
  den: Int64 4


In [29]:
c3=Complex{Rational{Int128}}(1//4,4)
typeof(c3)

Complex{Rational{Int128}}

### Data types

In [30]:
parse(Float64, "3.7")

3.7

In [31]:
@show Int64('a') 	# character to integer
@show Int64(2.0) 	# float to integer
#Int64(1.3) 		# inexact error
#Int64("a") 		# error no conversion possible
@show Float64(1) 	# integer to float
@show Bool(1) 		# boolean true
@show Bool(0) 		# boolean false
@show Char(89) 		# integer to char
@show zero(10.0) 	# zero of  arg type (Float64)
@show one(Int64) 	# one of type Int64
@show convert(Int64, 1.0)	# float to integer
@show parse(Int64, "1")

Int64('a') = 97
Int64(2.0) = 2
Float64(1) = 1.0
Bool(1) = true
Bool(0) = false
Char(89) = 'Y'
zero(10.0) = 0.0
one(Int64) = 1
convert(Int64, 1.0) = 1
parse(Int64, "1") = 1


1

In [32]:
using DataFrames

u = [1,3,4,missing, 7]

5-element Vector{Union{Missing, Int64}}:
 1
 3
 4
  missing
 7

In [33]:
@show Int <: Any
@show Int <: Union{Int, Float64}
@show typeof(nothing)
@show typeof(missing)


Int <: Any = true
Int <: Union{Int, Float64} = true
typeof(nothing) = Nothing
typeof(missing) = Missing


Missing

In [34]:
f(x) = println("2x+6= $(2x+6) "*"SUFFIX")
res = f(1.7)
typeof(res)

2x+6= 9.4 SUFFIX


Nothing

In [35]:
[nothing, Nothing]

2-element Vector{Union{Nothing, DataType}}:
 nothing
 Nothing

In [36]:
f(x,y) = x < y ? x-5 : x+5

f (generic function with 2 methods)

In [37]:
.+([1,2], [7,8])

2-element Vector{Int64}:
  8
 10

### Tuples

In [38]:
function f(a::Int)
    #return (a=a, b=a+5)
    return (;a, b=a+5)
end
res = f(3)


(a = 3, b = 8)

In [39]:
@macroexpand @NamedTuple{a::Int64, b::Int64}

:(Base.NamedTuple{(:a, :b), Base.Tuple{Int64, Int64}})

In [40]:
t = ("a", 1, 1, 2.0, [1,2,3]) 	
typeof(t)

Tuple{String, Int64, Int64, Float64, Vector{Int64}}

In [41]:
@show () 		# empty tuple
@show (1,) 		# one element tuple
@show ("a", 1) 	# two element tuple
@show ('a', false)::Tuple{Char, Bool} # tuple type assertion
@show x = (1, 2, 3)
@show x[1] 		# first element
@show x[1:2] 	# (1, 2) (tuple)
# x[4] 		# bounds error
# x[1] = 1 	# error - tuple is not mutable
@show a, b = x 	# tuple unpacking a==1, b==2


() = ()
(1,) = (1,)
("a", 1) = ("a", 1)
('a', false)::Tuple{Char, Bool} = ('a', false)
x = (1, 2, 3) = (1, 2, 3)
x[1] = 1
x[1:2] = (1, 2)
(a, b) = x = (1, 2, 3)


(1, 2, 3)

In [42]:
t = (3, 3.0)
typeof(t)

Tuple{Int64, Float64}

In [43]:
k = (1, "k",  1//5)
typeof(k)

Tuple{Int64, String, Rational{Int64}}

In [44]:
v = collect(3:10)
v[7:end]

2-element Vector{Int64}:
  9
 10

### Matrices

In [45]:
Matrix{String}(undef ,3,4)

3×4 Matrix{String}:
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef

In [46]:
Array{Char}(undef, 2, 3, 4) 	# 2x3x4 array of Chars
@show Array{Any}(undef, 2, 3) 	# 2x3 array of Any
@show zeros(5) 				# vector of Float64 zeros
@show ones(Int64, 2, 1) 	# 2x1 array of Int64 ones
@show trues(3), falses(3) 	# tuple of vector of trues and of falses

@show x = range(1, stop=2, length=5)  # iterator having 5 equally spaced elements
@show collect(x) 	# converts iterator to vector
@show 1:10 			# iterable from 1 to 10
@show 1:2:10 		# iterable from 1 to 9 with 2 skip
@show reshape(1:12, 3, 4)	# 3x4 array filled with 1:12 values


Array{Any}(undef, 2, 3) = Any[#undef #undef #undef; #undef #undef #undef]
zeros(5) = [0.0, 0.0, 0.0, 0.0, 0.0]
ones(Int64, 2, 1) = [1; 1;;]
(trues(3), falses(3)) = (Bool[1, 1, 1], Bool[0, 0, 0])
x = range(1, stop = 2, length = 5) = 1.0:0.25:2.0
collect(x) = [1.0, 1.25, 1.5, 1.75, 2.0]
1:10 = 1:10
1:2:10 = 1:2:9
reshape(1:12, 3, 4) = [1 4 7 10; 2 5 8 11; 3 6 9 12]


3×4 reshape(::UnitRange{Int64}, 3, 4) with eltype Int64:
 1  4  7  10
 2  5  8  11
 3  6  9  12

In [47]:
Matrix

Matrix (alias for Array{T, 2} where T)

In [48]:
y = Matrix{Int64}(undef, 2, 3)

2×3 Matrix{Int64}:
 8084067366094254176  6949177370342355040  27074788521435184
 6949160192081678432  6931145587411673136       413933764704

In [49]:
m = zeros( 4,5)
m[1,3] = 66
m
# 1-based numbering

4×5 Matrix{Float64}:
 0.0  0.0  66.0  0.0  0.0
 0.0  0.0   0.0  0.0  0.0
 0.0  0.0   0.0  0.0  0.0
 0.0  0.0   0.0  0.0  0.0

In [50]:
m[:,3] #array slicing

4-element Vector{Float64}:
 66.0
  0.0
  0.0
  0.0

In [51]:
a = reshape(Int128(1):Int128(12_000_000_000), 3_000, 4_000_000)
sum(a)

72000000006000000000

In [52]:
a = reshape(1:12, 3, 4)
display(a[:, 3:end]) # 3x2 matrix
display(a[:, 1]) # 3 element vector
display(a[1, :]) # 4 element vector


3×2 Matrix{Int64}:
 7  10
 8  11
 9  12

3-element Vector{Int64}:
 1
 2
 3

4-element Vector{Int64}:
  1
  4
  7
 10

### Data structures

In [53]:
mutable struct Point1
  x::Int
  y::Float64
  meta
end
p = Point1(0, 0.0, "Origin")
@show p
@show p.x 		# access field
p.meta = 2		# change field value
@show fieldnames(typeof(p)) # get names of instance fields
@show fieldnames(Point1); 	# get names of type fields


p = Point1(0, 0.0, "Origin")
p.x = 0
fieldnames(typeof(p)) = (:x, :y, :meta)
fieldnames(Point1) = (:x, :y, :meta)


In [54]:
fieldnames(typeof(p))

(:x, :y, :meta)

In [55]:
dump(:x)

Symbol x


In [56]:
dump(p)

Point1
  x: Int64 0
  y: Float64 0.0
  meta: Int64 2


In [57]:
fieldnames(typeof(p))

(:x, :y, :meta)

In [58]:
dump(:a)

Symbol a


In [59]:
@kwdef struct Point2
  x::Int64 = 1
  y::Float64 = 2.0
  meta
end
p2 = Point2(x=999, meta = "Origin")

Point2(999, 2.0, "Origin")

In [60]:
dump(p2)

Point2
  x: Int64 999
  y: Float64 2.0
  meta: String "Origin"


In [61]:
try
    p2.x = 33333
catch e
    println(e)
end

ErrorException("setfield!: immutable struct of type Point2 cannot be changed")


In [62]:
using Parameters
@with_kw mutable struct Point3
  x::Int64 = 1
  y::Float64 = 2.0
  meta
end
p3 = Point3(x=999, meta = "Origin")
p3.x = 66
p3

Point3
  x: Int64 66
  y: Float64 2.0
  meta: String "Origin"


In [63]:
Point3(;x=11,meta="ss")

Point3
  x: Int64 11
  y: Float64 2.0
  meta: String "ss"


In [64]:
struct MyPoint{T <: Real}
    x::T
    y::T
end

MyPoint(4,5)

MyPoint{Int64}(4, 5)

In [65]:
mutable struct MyPoint2{T <: Real}
    x::T
    y::T
    z::Union{T,Nothing}
end

### Dictionaries

In [66]:
x = Dict{Int, Float64}()
x[5] = 66.6
x[7] = 99

x

Dict{Int64, Float64} with 2 entries:
  5 => 66.6
  7 => 99.0

In [67]:
dump(4 => 7)

Pair{Int64, Int64}
  first: Int64 4
  second: Int64 7


In [68]:
y = Dict(:cat => 44, :dog=>57)

Dict{Symbol, Int64} with 2 entries:
  :cat => 44
  :dog => 57

In [69]:
x2 = Dict{Any, Any}()
x2[5] = 66.6
x2[7] = 99

x2

Dict{Any, Any} with 2 entries:
  5 => 66.6
  7 => 99

In [70]:
keys(y)

KeySet for a Dict{Symbol, Int64} with 2 entries. Keys:
  :cat
  :dog

In [71]:
Dict(1=>1, 1=>999)

Dict{Int64, Int64} with 1 entry:
  1 => 999

In [72]:
for (a, b) in y
    @show a, b
    
end

(a, b) = (:cat, 44)
(a, b) = (:dog, 57)


In [73]:
y[:cat]

44

In [74]:
typeof(1=>5)

Pair{Int64, Int64}

In [75]:
y = Dict(1=>5.5, 2=>4.5)

Dict{Int64, Float64} with 2 entries:
  2 => 4.5
  1 => 5.5

In [76]:
x = Dict{Int, Float64}() # empty dictionary mapping integers to floats
y = Dict(1=>5.5, 2=>4.5) 	# created dictionary
@show y[2] 					# get element
@show y[3] = 30.0 			# add element
@show haskey(y, 2) 			# check if key exists
@show keys(y), values(y) # iterators returning dictionary keys and values
@show delete!(y, 2)   # removing elements see also: pop!
@show get(y, 2, 777) # returns y[2] or 777 if not haskey(y,2)


y[2] = 4.5
y[3] = 30.0 = 30.0
haskey(y, 2) = true
(keys(y), values(y)) = ([2, 3, 1], [4.5, 30.0, 5.5])
delete!(y, 2) = Dict(3 => 30.0, 1 => 5.5)
get(y, 2, 777) = 777


777

### Text processing

In [77]:
x = 123
@show "$x + 3 = $(x+3)  3\$"

"$(x) + 3 = $(x + 3)  3\$" = "123 + 3 = 126  3\$"


"123 + 3 = 126  3\$"

In [78]:
@show "Hi " * "there!" 		# concatenation
@show "Ho " ^ 3 			# multiplication
@show string("a= ", 123.3) 	# joining elements to text
@show occursin("CD","ABCD") 	# occurence
@show "\"\n\t\$" # C-like escaping, additionally escape \$
                          # escaping - similiar to Matlab, Python, R
x = 123
@show "$x + 3 = $(x+3)"  # $ is an interpolation operator
@show "\$199" # that is why you need escaping

r = r"A|B" # full support for regular expressions
@show occursin(r, "CD") # false, not found
@show m = match(r, "ACBD"); # first regexp match


"Hi " * "there!" = "Hi there!"
"Ho " ^ 3 = "Ho Ho Ho "
string("a= ", 123.3) = "a= 123.3"
occursin("CD", "ABCD") = true
"\"\n\t\$" = "\"\n\t\$"
"$(x) + 3 = $(x + 3)" = "123 + 3 = 126"
"\$199" = "\$199"
occursin(r, "CD") = false
m = match(r, "ACBD") = RegexMatch("A")


In [79]:

x = 6

tekst = "hello $x and $(x*x+2x)"

"hello 6 and 48"

In [80]:
str = raw"c:\windows\newfolfder"

"c:\\windows\\newfolfder"

Note that `?` magic comment works only in Jupyter Notebook (not in Visual Studio Code)

In [81]:
?@raw_str

```
@raw_str -> String
```

Create a raw string without interpolation and unescaping. The exception is that quotation marks still must be escaped. Backslashes escape both quotation marks and other backslashes, but only when a sequence of backslashes precedes a quote character. Thus, 2n backslashes followed by a quote encodes n backslashes and the end of the literal while 2n+1 backslashes followed by a quote encodes n backslashes followed by a quote character.

# Examples

```jldoctest
julia> println(raw"\ $x")
\ $x

julia> println(raw"\"")
"

julia> println(raw"\\\"")
\"

julia> println(raw"\\x \\\"")
\\x \"
```


### Functions

In [82]:
f(x, y = 10) = x + y
# for this function the default value of y is 10
@show f(3, 2) # 5 is returned
@show f(3)    # 13 is returned


f(3, 2) = 5
f(3) = (a = 3, b = 8)


(a = 3, b = 8)

In [83]:
function g(x::Int, y::Int) # limit arg type
  return y, x # tuple returned
end

g(x::Int, y::Bool) = x * y # multiple dispatch
g(x, y) = x - y
g(x::Real, y::Real) = x - y

methods(g) # list of methods for g


# 4 methods for generic function "g" from Main:
 [1] g(x::Int64, y::Bool)
     @ In[83]:5
 [2] g(x::Int64, y::Int64)
     @ In[83]:1
 [3] g(x::Real, y::Real)
     @ In[83]:7
 [4] g(x, y)
     @ In[83]:6

In [84]:
function g(x::Int, y::Int) # limit arg type
  return y, x # tuple returned
end

g(x::Int, y::Bool) = x * y # multiple dispatch

@show g(1,2)
@show g(1, true)


g(1, 2) = (2, 1)
g(1, true) = 1


1

In [85]:
methods(g)

# 4 methods for generic function "g" from Main:
 [1] g(x::Int64, y::Bool)
     @ In[84]:5
 [2] g(x::Int64, y::Int64)
     @ In[84]:1
 [3] g(x::Real, y::Real)
     @ In[83]:7
 [4] g(x, y)
     @ In[83]:6

In [86]:
@show g(1,4)
@show g(1,true)
methods(g)

g(1, 4) = (4, 1)
g(1, true) = 1


# 4 methods for generic function "g" from Main:
 [1] g(x::Int64, y::Bool)
     @ In[84]:5
 [2] g(x::Int64, y::Int64)
     @ In[84]:1
 [3] g(x::Real, y::Real)
     @ In[83]:7
 [4] g(x, y)
     @ In[83]:6

### Operators

In [87]:
y = collect(1:10)


10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [88]:
collect(y')

1×10 Matrix{Int64}:
 1  2  3  4  5  6  7  8  9  10

In [89]:
[1 2] .< [2 1]

1×2 BitMatrix:
 1  0

In [90]:
@show true || false # binary or operator (singeltons only)
@show 1 < 2 < 3     # condition chaining  is OK
@show [1 2] .< [2 1] # vectorization via dot operator "."
@show a = 5
@show 2a + 2(a+1) # multiplication can be ommited
@show x = [1 2 3]	  #matrix 1×3 Array{Int64,2}
@show y = [1, 2, 3]  #matrix 3-elements Array{Int64,1}
# vectors are vecticar and are different concept than horizontal 1-row matrix
#x + y # error
@show x .+ y # 3x3 matrix, dimension broadcasting
@show x + y' # 1x3 matrix
@show x * y; # array multiplication, 1-element vector (not scalar)


true || false = true
1 < 2 < 3 = true
[1 2] .< [2 1] = Bool[1 0]
a = 5 = 5
2a + 2 * (a + 1) = 22
x = [1 2 3] = [1 2 3]
y = [1, 2, 3] = [1, 2, 3]
x .+ y = [2 3 4; 3 4 5; 4 5 6]
x + y' = [2 4 6]
x * y = [14]


1-element Vector{Int64}:
 14

In [91]:
f(x,y) =  x<y ? x : y

f (generic function with 3 methods)

In [92]:
f(10,30)

10

In [93]:
a=  [1,2,3]
b=  [0,5,6]

3-element Vector{Int64}:
 0
 5
 6

In [94]:
f.(a,b)

3-element Vector{Int64}:
 0
 2
 3

In [95]:
a .* b

3-element Vector{Int64}:
  0
 10
 18

### Python integration

In [96]:
println(pwd())

C:\AAABIBLIOTEKA\NCN2\SSC2024\2024_Julia_Krakow\1_Basics


In [97]:
using CondaPkg, Pkg
pkg"conda status"


CondaPkg Status C:\AAABIBLIOTEKA\NCN2\SSC2024\2024_Julia_Krakow\CondaPkg.toml
Environment
  C:\AAABIBLIOTEKA\NCN2\SSC2024\2024_Julia_Krakow\.CondaPkg\env
Packages
  folium v0.17.0
  jupyter v1.1.1
Channels
  conda-forge


In [98]:
using PythonCall
sys = pyimport("sys")

Python: <module 'sys' (built-in)>

In [99]:
pth = sys.executable

Python: 'C:\\AAABIBLIOTEKA\\NCN2\\SSC2024\\2024_Julia_Krakow\\.CondaPkg\\env\\python.exe'

In [100]:
typeof(pth)

Py

In [101]:
string(pth)

"C:\\AAABIBLIOTEKA\\NCN2\\SSC2024\\2024_Julia_Krakow\\.CondaPkg\\env\\python.exe"

In [102]:
b = @pyeval("{ (x,y):x*y for x in range(1,5) for y in range(1,3) }")

Python: {(1, 1): 1, (1, 2): 2, (2, 1): 2, (2, 2): 4, (3, 1): 3, (3, 2): 6, (4, 1): 4, (4, 2): 8}

In [103]:
@pyconvert(Dict, b)

Dict{Tuple{Int64, Int64}, Int64} with 8 entries:
  (3, 2) => 6
  (1, 2) => 2
  (3, 1) => 3
  (1, 1) => 1
  (4, 2) => 8
  (4, 1) => 4
  (2, 2) => 4
  (2, 1) => 2